services:
  influxdb:
    image: influxdb:alpine
    restart: unless-stopped
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 2s
      timeout: 10s
      retries: 10
    environment:
      TZ: Europe/Lisbon
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb-admin-token
      DOCKER_INFLUXDB_INIT_ORG: pinheiro 
      DOCKER_INFLUXDB_INIT_BUCKET: automation
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.automation_influxdb.rule=Host(`influxdb.pinheiro.s3n.io`)'
      - 'traefik.http.routers.automation_influxdb.entrypoints=web'
      - 'traefik.http.services.automation_influxdb.loadbalancer.server.port=8086'
      - 'traefik.docker.network=infra_traefik'
    networks:
      - default
      - infra_traefik
    secrets:
      - influxdb-admin-username
      - influxdb-admin-password
      - influxdb-admin-token
    volumes:
      - ${CONFIG_PATH}/influxdb/data:/var/lib/influxdb
      - ${CONFIG_PATH}/influxdb/config:/etc/influxdb

  home-assistant:
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    healthcheck:
      test: "curl -sS http://localhost:8123"
      interval: 2s
      timeout: 5s
      retries: 10
    depends_on:
      influxdb:
        condition: service_healthy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.automation_home-assistant.rule=Host(`home-assistant.pinheiro.s3n.io`)'
      - 'traefik.http.routers.automation_home-assistant.entrypoints=web'
      - 'traefik.http.services.automation_home-assistant.loadbalancer.server.port=8123'
      - 'traefik.docker.network=infra_traefik'
    ports:
      - "5683:5683/udp"
      - "5683:5683/tcp"
    environment:
      PUID: 1001
      GUID: 1001
      TZ: Europe/Lisbon
    networks:
      - default #Needed to reach influxdb and other containers on the default network
      - infra_traefik
    volumes:
      - ${CONFIG_PATH}/hass:/config

  nodered:
    image: nodered/node-red:latest
    restart: unless-stopped
    depends_on:
      home-assistant:
        condition: service_healthy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.automation_nodered.rule=Host(`nodered.pinheiro.s3n.io`)'
      - 'traefik.http.routers.automation_nodered.entrypoints=web'
      - 'traefik.http.services.automation_nodered.loadbalancer.server.port=1880'
      - 'traefik.docker.network=infra_traefik'
    environment:
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
    volumes:
      - ${CONFIG_PATH}/node-red:/data

secrets:
  influxdb-admin-username:
    file: ${CONFIG_PATH}/influxdb/secrets/.env.influxdb-admin-username
  influxdb-admin-password:
    file: ${CONFIG_PATH}/influxdb/secrets/.env.influxdb-admin-password
  influxdb-admin-token:
    file: ${CONFIG_PATH}/influxdb/secrets/.env.influxdb-admin-token

networks:
  infra_traefik:
    external: true
