services:  
  home-assistant:
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.automation_home-assistant.rule=Host(`home-assistant.pinheiro.s3n.io`)'
      - 'traefik.http.routers.automation_home-assistant.entrypoints=web'
      - 'traefik.http.services.automation_home-assistant.loadbalancer.server.port=8123'
      - 'traefik.docker.network=infra_traefik'
    ports:
      - "5683:5683/udp"
      - "5683:5683/tcp"
    environment:
      PUID: 1001
      GUID: 1001
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
    volumes:
      - ${CONFIG_PATH}/hass:/config

  nodered:
    image: nodered/node-red:latest
    restart: unless-stopped
    depends_on:
      - home-assistant
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.automation_nodered.rule=Host(`nodered.pinheiro.s3n.io`)'
      - 'traefik.http.routers.automation_nodered.entrypoints=web'
      - 'traefik.http.services.automation_nodered.loadbalancer.server.port=1880'
      - 'traefik.docker.network=infra_traefik'
    environment:
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
    volumes:
      - ${CONFIG_PATH}/node-red:/data

networks:
  infra_traefik:
    external: true
